{
  "name": "SemanticModel",
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/SOHEILT;BankingDW",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "SOHEILT",
            "database": "BankingDW"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "Username": "sa",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "DW Dim_Customer",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "CustomerID",
            "dataType": "string",
            "sourceColumn": "CustomerID"
          },
          {
            "name": "DateOfBirth",
            "dataType": "dateTime",
            "sourceColumn": "DateOfBirth",
            "displayFolder": "Demographics"
          },
          {
            "name": "Age",
            "dataType": "int64",
            "sourceColumn": "Age",
            "displayFolder": "Demographics"
          },
          {
            "name": "AgeGroup",
            "dataType": "string",
            "sourceColumn": "AgeGroup",
            "displayFolder": "Demographics"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender",
            "displayFolder": "Demographics"
          },
          {
            "name": "Location",
            "dataType": "string",
            "sourceColumn": "Location",
            "displayFolder": "Location"
          },
          {
            "name": "LocationKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "LocationKey"
          },
          {
            "name": "CustomerType",
            "dataType": "string",
            "sourceColumn": "CustomerType"
          },
          {
            "name": "FirstTransactionDate",
            "dataType": "dateTime",
            "sourceColumn": "FirstTransactionDate"
          },
          {
            "name": "StartDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "StartDate"
          },
          {
            "name": "EndDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "EndDate"
          },
          {
            "name": "IsCurrent",
            "dataType": "boolean",
            "isHidden": true,
            "sourceColumn": "IsCurrent"
          },
          {
            "name": "CreatedDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "CreatedDate"
          },
          {
            "name": "ModifiedDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "ModifiedDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/SOHEILT;BankingDW\",",
                "    DW_Dim_Customer = Source{[Schema=\"DW\",Item=\"Dim_Customer\"]}[Data]",
                "in",
                "    DW_Dim_Customer"
              ]
            }
          }
        ]
      },
      {
        "name": "DW Dim_Date",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DateKey",
            "displayFolder": "Date Attributes"
          },
          {
            "name": "FullDateTime",
            "dataType": "dateTime",
            "sourceColumn": "FullDateTime",
            "displayFolder": "Time Attributes"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "Date",
            "displayFolder": "Date Attributes"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Year"
          },
          {
            "name": "YearName",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "YearName"
          },
          {
            "name": "Quarter",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Quarter"
          },
          {
            "name": "QuarterName",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "QuarterName"
          },
          {
            "name": "YearQuarter",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "YearQuarter"
          },
          {
            "name": "Month",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Month"
          },
          {
            "name": "MonthName",
            "dataType": "string",
            "sourceColumn": "MonthName",
            "displayFolder": "Date Attributes"
          },
          {
            "name": "MonthNameShort",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MonthNameShort"
          },
          {
            "name": "YearMonth",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "YearMonth"
          },
          {
            "name": "YearMonthName",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "YearMonthName"
          },
          {
            "name": "Day",
            "dataType": "int64",
            "sourceColumn": "Day"
          },
          {
            "name": "DayOfWeek",
            "dataType": "int64",
            "sourceColumn": "DayOfWeek",
            "displayFolder": "Date Attributes"
          },
          {
            "name": "DayName",
            "dataType": "string",
            "sourceColumn": "DayName",
            "displayFolder": "Date Attributes"
          },
          {
            "name": "DayNameShort",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DayNameShort"
          },
          {
            "name": "DayOfYear",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DayOfYear"
          },
          {
            "name": "WeekOfYear",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "WeekOfYear"
          },
          {
            "name": "WeekOfMonth",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "WeekOfMonth"
          },
          {
            "name": "FiscalYear",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FiscalYear"
          },
          {
            "name": "FiscalQuarter",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FiscalQuarter"
          },
          {
            "name": "FiscalMonth",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FiscalMonth"
          },
          {
            "name": "Time",
            "dataType": "dateTime",
            "sourceColumn": "Time",
            "displayFolder": "Time Attributes"
          },
          {
            "name": "Hour",
            "dataType": "int64",
            "sourceColumn": "Hour",
            "displayFolder": "Time Attributes"
          },
          {
            "name": "HourName",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "HourName"
          },
          {
            "name": "Minute",
            "dataType": "int64",
            "sourceColumn": "Minute",
            "displayFolder": "Time Attributes"
          },
          {
            "name": "TimeOfDay",
            "dataType": "string",
            "sourceColumn": "TimeOfDay",
            "displayFolder": "Time Attributes"
          },
          {
            "name": "IsWeekend",
            "dataType": "boolean",
            "sourceColumn": "IsWeekend",
            "displayFolder": "Flags"
          },
          {
            "name": "IsHoliday",
            "dataType": "boolean",
            "sourceColumn": "IsHoliday",
            "displayFolder": "Flags"
          },
          {
            "name": "IsWorkingDay",
            "dataType": "boolean",
            "sourceColumn": "IsWorkingDay",
            "displayFolder": "Flags"
          },
          {
            "name": "IsToday",
            "dataType": "boolean",
            "isHidden": true,
            "sourceColumn": "IsToday"
          },
          {
            "name": "IsYesterday",
            "dataType": "boolean",
            "isHidden": true,
            "sourceColumn": "IsYesterday"
          },
          {
            "name": "IsCurrentMonth",
            "dataType": "boolean",
            "isHidden": true,
            "sourceColumn": "IsCurrentMonth"
          },
          {
            "name": "IsCurrentQuarter",
            "dataType": "boolean",
            "isHidden": true,
            "sourceColumn": "IsCurrentQuarter"
          },
          {
            "name": "IsCurrentYear",
            "dataType": "boolean",
            "isHidden": true,
            "sourceColumn": "IsCurrentYear"
          },
          {
            "name": "CreatedDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "CreatedDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/SOHEILT;BankingDW\",",
                "    DW_Dim_Date = Source{[Schema=\"DW\",Item=\"Dim_Date\"]}[Data]",
                "in",
                "    DW_Dim_Date"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Calendar",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month"
              },
              {
                "name": "Date",
                "ordinal": 3,
                "column": "Date"
              }
            ]
          }
        ]
      },
      {
        "name": "DW Dim_Location",
        "columns": [
          {
            "name": "LocationKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "LocationKey"
          },
          {
            "name": "LocationCode",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "LocationCode"
          },
          {
            "name": "LocationName",
            "dataType": "string",
            "sourceColumn": "LocationName"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "displayFolder": "Geography"
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State",
            "displayFolder": "Geography"
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country",
            "displayFolder": "Geography"
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "displayFolder": "Geography"
          },
          {
            "name": "Latitude",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Latitude"
          },
          {
            "name": "Longitude",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Longitude"
          },
          {
            "name": "LocationType",
            "dataType": "string",
            "sourceColumn": "LocationType"
          },
          {
            "name": "CreatedDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "CreatedDate"
          },
          {
            "name": "ModifiedDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "ModifiedDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/SOHEILT;BankingDW\",",
                "    DW_Dim_Location = Source{[Schema=\"DW\",Item=\"Dim_Location\"]}[Data]",
                "in",
                "    DW_Dim_Location"
              ]
            }
          }
        ]
      },
      {
        "name": "DW Dim_Segment",
        "columns": [
          {
            "name": "SegmentKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SegmentKey"
          },
          {
            "name": "SegmentCode",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "SegmentCode"
          },
          {
            "name": "SegmentName",
            "dataType": "string",
            "sourceColumn": "SegmentName"
          },
          {
            "name": "SegmentType",
            "dataType": "string",
            "sourceColumn": "SegmentType"
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description",
            "displayFolder": "Segmentation Rules"
          },
          {
            "name": "RecencyMin",
            "dataType": "int64",
            "sourceColumn": "RecencyMin",
            "displayFolder": "Segmentation Rules"
          },
          {
            "name": "RecencyMax",
            "dataType": "int64",
            "sourceColumn": "RecencyMax",
            "displayFolder": "Segmentation Rules"
          },
          {
            "name": "FrequencyMin",
            "dataType": "int64",
            "sourceColumn": "FrequencyMin",
            "displayFolder": "Segmentation Rules"
          },
          {
            "name": "FrequencyMax",
            "dataType": "int64",
            "sourceColumn": "FrequencyMax",
            "displayFolder": "Segmentation Rules"
          },
          {
            "name": "DisplayOrder",
            "dataType": "int64",
            "sourceColumn": "DisplayOrder"
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "Color"
          },
          {
            "name": "IsActive",
            "dataType": "boolean",
            "sourceColumn": "IsActive"
          },
          {
            "name": "StartDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "StartDate"
          },
          {
            "name": "EndDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "EndDate"
          },
          {
            "name": "CreatedDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "CreatedDate"
          },
          {
            "name": "ModifiedDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "ModifiedDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/SOHEILT;BankingDW\",",
                "    DW_Dim_Segment = Source{[Schema=\"DW\",Item=\"Dim_Segment\"]}[Data]",
                "in",
                "    DW_Dim_Segment"
              ]
            }
          }
        ]
      },
      {
        "name": "DW Fact_CustomerSnapshot",
        "columns": [
          {
            "name": "SnapshotKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SnapshotKey"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DateKey"
          },
          {
            "name": "SegmentKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SegmentKey"
          },
          {
            "name": "TransactionCount",
            "dataType": "int64",
            "sourceColumn": "TransactionCount",
            "displayFolder": "Transaction Metrics"
          },
          {
            "name": "TotalTransactionAmount",
            "dataType": "double",
            "sourceColumn": "TotalTransactionAmount",
            "displayFolder": "Transaction Metrics"
          },
          {
            "name": "AvgTransactionAmount",
            "dataType": "double",
            "sourceColumn": "AvgTransactionAmount",
            "displayFolder": "Transaction Metrics"
          },
          {
            "name": "MinTransactionAmount",
            "dataType": "double",
            "sourceColumn": "MinTransactionAmount",
            "displayFolder": "Transaction Metrics"
          },
          {
            "name": "MaxTransactionAmount",
            "dataType": "double",
            "sourceColumn": "MaxTransactionAmount",
            "displayFolder": "Transaction Metrics"
          },
          {
            "name": "DaysSinceLastTransaction",
            "dataType": "int64",
            "sourceColumn": "DaysSinceLastTransaction",
            "displayFolder": "RF Analysis"
          },
          {
            "name": "RecencyScore",
            "dataType": "int64",
            "sourceColumn": "RecencyScore",
            "displayFolder": "RF Analysis"
          },
          {
            "name": "FrequencyScore",
            "dataType": "int64",
            "sourceColumn": "FrequencyScore",
            "displayFolder": "RF Analysis"
          },
          {
            "name": "LoyaltyScore",
            "dataType": "double",
            "sourceColumn": "LoyaltyScore",
            "displayFolder": "RF Analysis"
          },
          {
            "name": "SatisfactionScore",
            "dataType": "double",
            "sourceColumn": "SatisfactionScore",
            "displayFolder": "Customer Behavior"
          },
          {
            "name": "ComplaintFlag",
            "dataType": "boolean",
            "sourceColumn": "ComplaintFlag",
            "displayFolder": "Customer Behavior"
          },
          {
            "name": "ChurnFlag",
            "dataType": "boolean",
            "sourceColumn": "ChurnFlag",
            "displayFolder": "Churn & Risk"
          },
          {
            "name": "AtRiskFlag",
            "dataType": "boolean",
            "sourceColumn": "AtRiskFlag",
            "displayFolder": "Churn & Risk"
          },
          {
            "name": "TrendCategory",
            "dataType": "string",
            "sourceColumn": "TrendCategory",
            "displayFolder": "Trend Analysis"
          },
          {
            "name": "PreviousMonthTransactionCount",
            "dataType": "int64",
            "sourceColumn": "PreviousMonthTransactionCount",
            "displayFolder": "Trend Analysis"
          },
          {
            "name": "GrowthRate",
            "dataType": "double",
            "sourceColumn": "GrowthRate",
            "displayFolder": "Trend Analysis"
          },
          {
            "name": "FinalAccountBalance",
            "dataType": "double",
            "sourceColumn": "FinalAccountBalance"
          },
          {
            "name": "ETLLoadDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "ETLLoadDate"
          },
          {
            "name": "ETLBatchID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ETLBatchID"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/SOHEILT;BankingDW\",",
                "    DW_Fact_CustomerSnapshot = Source{[Schema=\"DW\",Item=\"Fact_CustomerSnapshot\"]}[Data]",
                "in",
                "    DW_Fact_CustomerSnapshot"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Total Customers",
            "expression": [
              " ",
              "DISTINCTCOUNT('DW Dim_Customer'[CustomerID])"
            ],
            "formatString": "#,0",
            "displayFolder": "Customer Metrics"
          },
          {
            "name": "Avg Transaction Frequency",
            "expression": [
              " ",
              "AVERAGE('DW Fact_CustomerSnapshot'[TransactionCount])"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Customer Metrics"
          },
          {
            "name": "Active Customers",
            "expression": [
              " ",
              "VAR MaxDateInData = ",
              "    CALCULATE(",
              "        MAX('DW Fact_CustomerSnapshot'[DateKey]),",
              "        REMOVEFILTERS('DW Dim_Date')",
              "    )",
              "RETURN",
              "CALCULATE(",
              "    DISTINCTCOUNT('DW Fact_CustomerSnapshot'[CustomerKey]),",
              "    'DW Fact_CustomerSnapshot'[DaysSinceLastTransaction] <= 30,",
              "    'DW Fact_CustomerSnapshot'[DateKey] = MaxDateInData",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Customer Metrics"
          },
          {
            "name": "Active Customer Rate",
            "expression": [
              " ",
              "DIVIDE([Active Customers], [Total Customers], 0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Customer Metrics"
          },
          {
            "name": "Churned Customers",
            "expression": [
              " ",
              "VAR MaxDateInData = ",
              "    CALCULATE(",
              "        MAX('DW Fact_CustomerSnapshot'[DateKey]),",
              "        REMOVEFILTERS('DW Dim_Date')",
              "    )",
              "RETURN",
              "CALCULATE(",
              "    DISTINCTCOUNT('DW Fact_CustomerSnapshot'[CustomerKey]),",
              "    'DW Fact_CustomerSnapshot'[ChurnFlag] = TRUE,",
              "    'DW Fact_CustomerSnapshot'[DateKey] = MaxDateInData",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Churn & Retention"
          },
          {
            "name": "Churn Rate",
            "expression": [
              " ",
              "DIVIDE([Churned Customers], [Total Customers], 0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Churn & Retention"
          },
          {
            "name": "Retention Rate",
            "expression": " 1 - [Churn Rate]",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Churn & Retention"
          },
          {
            "name": "At-Risk Customers",
            "expression": [
              " ",
              "VAR MaxDateInData = ",
              "    CALCULATE(",
              "        MAX('DW Fact_CustomerSnapshot'[DateKey]),",
              "        REMOVEFILTERS()",
              "    )",
              "VAR Result = ",
              "    CALCULATE(",
              "        DISTINCTCOUNT('DW Fact_CustomerSnapshot'[CustomerKey]),",
              "        'DW Fact_CustomerSnapshot'[DaysSinceLastTransaction] > 60,",
              "        'DW Fact_CustomerSnapshot'[DaysSinceLastTransaction] <= 90,",
              "        'DW Fact_CustomerSnapshot'[DateKey] = MaxDateInData",
              "    )",
              "RETURN",
              "IF(ISBLANK(Result), 0, Result)"
            ],
            "formatString": "#,0",
            "displayFolder": "Churn & Retention"
          },
          {
            "name": "Avg Loyalty Score",
            "expression": [
              " ",
              "VAR MaxDateInData = ",
              "    CALCULATE(",
              "        MAX('DW Fact_CustomerSnapshot'[DateKey]),",
              "        REMOVEFILTERS('DW Dim_Date')",
              "    )",
              "RETURN",
              "CALCULATE(",
              "    AVERAGE('DW Fact_CustomerSnapshot'[LoyaltyScore]),",
              "    'DW Fact_CustomerSnapshot'[DateKey] = MaxDateInData",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Loyalty & Satisfaction"
          },
          {
            "name": "Avg Satisfaction Score",
            "expression": [
              " ",
              "VAR MaxDateInData = ",
              "    CALCULATE(",
              "        MAX('DW Fact_CustomerSnapshot'[DateKey]),",
              "        REMOVEFILTERS('DW Dim_Date')",
              "    )",
              "RETURN",
              "CALCULATE(",
              "    AVERAGE('DW Fact_CustomerSnapshot'[SatisfactionScore]),",
              "    'DW Fact_CustomerSnapshot'[DateKey] = MaxDateInData",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Loyalty & Satisfaction"
          },
          {
            "name": "Avg Recency Days",
            "expression": [
              " ",
              "VAR MaxDateInData = ",
              "    CALCULATE(",
              "        MAX('DW Fact_CustomerSnapshot'[DateKey]),",
              "        REMOVEFILTERS('DW Dim_Date')",
              "    )",
              "RETURN",
              "CALCULATE(",
              "    AVERAGE('DW Fact_CustomerSnapshot'[DaysSinceLastTransaction]),",
              "    'DW Fact_CustomerSnapshot'[DateKey] = MaxDateInData",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "displayFolder": "Loyalty & Satisfaction"
          },
          {
            "name": "Total Transaction Amount",
            "expression": " SUM('DW Fact_CustomerSnapshot'[TotalTransactionAmount])",
            "formatString": "\"₹\"#,0.00;#,0.00 -\"₹\";\"₹\"#,0.00",
            "displayFolder": "Transactions",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1081\" DisplayName=\"₹ Hindi (India)\" Symbol=\"₹\" PositivePattern=\"0\" NegativePattern=\"12\" /></Format>"
              }
            ]
          },
          {
            "name": "Total Transactions",
            "expression": [
              " ",
              "SUM('DW Fact_CustomerSnapshot'[TransactionCount])"
            ],
            "formatString": "#,0",
            "displayFolder": "Transactions"
          },
          {
            "name": "Avg Transaction Amount",
            "expression": [
              " ",
              "DIVIDE([Total Transaction Amount], [Total Transactions], 0)"
            ],
            "formatString": "\"₹\"#,0.00;#,0.00 -\"₹\";\"₹\"#,0.00",
            "displayFolder": "Transactions",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1081\" DisplayName=\"₹ Hindi (India)\" Symbol=\"₹\" PositivePattern=\"0\" NegativePattern=\"12\" /></Format>"
              }
            ]
          },
          {
            "name": "Total Balance",
            "expression": [
              " ",
              "SUM('DW Fact_CustomerSnapshot'[FinalAccountBalance])"
            ],
            "formatString": "\"₹\"#,0.00;#,0.00 -\"₹\";\"₹\"#,0.00",
            "displayFolder": "Transactions",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1081\" DisplayName=\"₹ Hindi (India)\" Symbol=\"₹\" PositivePattern=\"0\" NegativePattern=\"12\" /></Format>"
              }
            ]
          },
          {
            "name": "Customers with Complaints",
            "expression": [
              " ",
              "VAR MaxDateInData = ",
              "    CALCULATE(",
              "        MAX('DW Fact_CustomerSnapshot'[DateKey]),",
              "        REMOVEFILTERS('DW Dim_Date')",
              "    )",
              "RETURN",
              "CALCULATE(",
              "    DISTINCTCOUNT('DW Fact_CustomerSnapshot'[CustomerKey]),",
              "    'DW Fact_CustomerSnapshot'[ComplaintFlag] = TRUE,",
              "    'DW Fact_CustomerSnapshot'[DateKey] = MaxDateInData",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Behavior"
          },
          {
            "name": "Complaint Rate",
            "expression": [
              " ",
              "DIVIDE([Customers with Complaints], [Total Customers], 0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Behavior"
          },
          {
            "name": "Avg Growth Rate",
            "expression": [
              " ",
              "VAR MaxDateInData = ",
              "    CALCULATE(",
              "        MAX('DW Fact_CustomerSnapshot'[DateKey]),",
              "        REMOVEFILTERS()",
              "    )",
              "RETURN",
              "CALCULATE(",
              "    AVERAGE('DW Fact_CustomerSnapshot'[GrowthRate]),",
              "    'DW Fact_CustomerSnapshot'[DateKey] = MaxDateInData",
              ") / 100"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Behavior"
          },
          {
            "name": "Customer Count by Segment",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT('DW Fact_CustomerSnapshot'[CustomerKey]),",
              "    KEEPFILTERS('DW Dim_Segment')",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Segments"
          },
          {
            "name": "Segment %",
            "expression": [
              " ",
              "DIVIDE(",
              "    [Customer Count by Segment],",
              "    CALCULATE([Total Customers], ALLSELECTED('DW Dim_Segment')),",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Segments"
          },
          {
            "name": "Promoters",
            "expression": [
              " ",
              "VAR MaxDateInData = ",
              "    CALCULATE(",
              "        MAX('DW Fact_CustomerSnapshot'[DateKey]),",
              "        REMOVEFILTERS('DW Dim_Date')",
              "    )",
              "RETURN",
              "CALCULATE(",
              "    DISTINCTCOUNT('DW Fact_CustomerSnapshot'[CustomerKey]),",
              "    'DW Fact_CustomerSnapshot'[SatisfactionScore] >= 4,",
              "    'DW Fact_CustomerSnapshot'[DateKey] = MaxDateInData",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "NPS"
          },
          {
            "name": "Detractors",
            "expression": [
              " ",
              "VAR MaxDateInData = ",
              "    CALCULATE(",
              "        MAX('DW Fact_CustomerSnapshot'[DateKey]),",
              "        REMOVEFILTERS('DW Dim_Date')",
              "    )",
              "RETURN",
              "CALCULATE(",
              "    DISTINCTCOUNT('DW Fact_CustomerSnapshot'[CustomerKey]),",
              "    'DW Fact_CustomerSnapshot'[SatisfactionScore] <= 2,",
              "    'DW Fact_CustomerSnapshot'[DateKey] = MaxDateInData",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "NPS"
          },
          {
            "name": "NPS Score",
            "expression": [
              " ",
              "DIVIDE([Promoters], [Total Customers], 0) - DIVIDE([Detractors], [Total Customers], 0)",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "NPS"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "2746f1c7-d632-4aad-a01c-878b1b4ea868",
        "fromTable": "DW Dim_Customer",
        "fromColumn": "LocationKey",
        "toTable": "DW Dim_Location",
        "toColumn": "LocationKey"
      },
      {
        "name": "e2c91893-a76c-4c33-ba39-0fdac02899a4",
        "fromTable": "DW Fact_CustomerSnapshot",
        "fromColumn": "CustomerKey",
        "toTable": "DW Dim_Customer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "8c36f21f-1eaa-4f45-a8d3-80e654729f09",
        "fromTable": "DW Fact_CustomerSnapshot",
        "fromColumn": "DateKey",
        "toTable": "DW Dim_Date",
        "toColumn": "DateKey"
      },
      {
        "name": "16cfbf4d-f5e1-4cd6-b0c9-6f3e11d6062a",
        "fromTable": "DW Fact_CustomerSnapshot",
        "fromColumn": "SegmentKey",
        "toTable": "DW Dim_Segment",
        "toColumn": "SegmentKey"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "700"
      }
    ]
  },
  "id": "SemanticModel"
}